# Generated by Django 5.1 on 2024-08-28 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_espacocoworking_proprietario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='espacocoworking',
            options={'ordering': ['nome'], 'verbose_name': 'Espaço de Coworking', 'verbose_name_plural': 'Espaços de Coworking'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['data_reserva', 'hora_inicio'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
