# Generated by Django 5.1 on 2024-08-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_alter_espacocoworking_options_alter_reserva_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='espacocoworking',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='espacocoworking',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
